### ISSUE TITLE
Don't we need to check if it isn't expired?

### ISSUE THREAD

**Issue by notflip** [farbodsalimi/react-redux-jwt-authentication-boilerplate#2]
https://github.com/farbodsalimi/react-redux-jwt-authentication-boilerplate/blob/4de5339c7ba7ada5819f290e4583f0a846700c8f/client/src/index.js#L34

**Comment by farbodsalimi** [comment]
@notflip No in this boilerplate code, I don't check the token expiration time, however, if you like please feel free to make a PR for it.
